name: release
on:
  release:
    types: [published]
    tags:
      - v*

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python 3.10
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          architecture: x64

      - name: Build sdist and wheel
        run: |
          pip install --upgrade setuptools pip wheel
          python3 setup.py sdist
          python3 setup.py bdist_wheel

      - name: Push release to PyPI
        if: github.event_name == 'release'
        run: |
          pip install --upgrade twine
          twine check dist/*
          twine upload dist/*
