name: Tests

on: [push, pull_request]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  tests-coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Run tests
        run: |
          pip install -U pip pytest pytest-cov coverage
          # code deps
          pip install "PyYaml>=5.3,<7.0" "tzdata>=2022.7" "iso3166>=2.1.1"
          PYTHONPATH=src pytest --cov offspot_runtime.checks --cov-report term-missing -v
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
